package brut.apktool.license;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

public final class LicenseManifestGenerator {
    private LicenseManifestGenerator() {
    }

    public static void main(String[] args) throws IOException {
        Path input = args.length > 0 ? Paths.get(args[0]) : Paths.get("build/reports/licenses/licenses.json");
        Path output = args.length > 1 ? Paths.get(args[1]) : Paths.get("LICENSE_MANIFEST.md");
        if (!Files.exists(input)) {
            throw new IOException("License inventory not found: " + input);
        }
        Gson gson = new GsonBuilder().create();
        String json = Files.readString(input, StandardCharsets.UTF_8);
        LicenseScanner.LicenseInventory inventory = gson.fromJson(json, LicenseScanner.LicenseInventory.class);
        String markdown = render(inventory);
        Files.writeString(output, markdown, StandardCharsets.UTF_8);
    }

    private static String render(LicenseScanner.LicenseInventory inventory) {
        StringBuilder builder = new StringBuilder();
        builder.append("# License Manifest\n\n");
        builder.append("## Third-Party Dependencies\n\n");
        builder.append("| Artifact | Version | License | Author | Source |\n");
        builder.append("|---|---|---|---|---|\n");
        if (inventory.dependencies != null) {
            inventory.dependencies.forEach(dep -> builder.append('|')
                .append(escape(dep.artifact)).append(" | ")
                .append(escape(dep.version)).append(" | ")
                .append(escape(dep.license)).append(" | ")
                .append(escape(dep.author)).append(" | ")
                .append(escape(dep.url)).append(" |\n"));
        }
        builder.append('\n');
        builder.append("## Internal Components\n\n");
        builder.append("| Component | License | Author |\n");
        builder.append("|---|---|---|\n");
        if (inventory.internalComponents != null) {
            inventory.internalComponents.forEach(component -> builder.append('|')
                .append(escape(component.component)).append(" | ")
                .append(escape(component.license)).append(" | ")
                .append(escape(component.author)).append(" |\n"));
        }
        builder.append('\n');
        builder.append("_Generated by LicenseManifestGenerator._\n");
        return builder.toString();
    }

    private static String escape(String input) {
        return input == null ? "" : input.replace("|", "\\|");
    }
}
